# Generated by Django 4.0.4 on 2022-05-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_tag_assets_asset_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name_plural': 'Strategies'},
        ),
    ]
