# Generated by Django 4.0.4 on 2022-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_strategy_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='sma_l',
            new_name='window_l',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='sma_m',
            new_name='window_m',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='sma_s',
            new_name='window_s',
        ),
        migrations.AddField(
            model_name='strategy',
            name='lag',
            field=models.IntegerField(default=7),
        ),
    ]
