# Generated by Django 4.0.4 on 2022-05-31 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_sma_l_strategy_window_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='algorithm',
        ),
        migrations.AddField(
            model_name='strategy',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.asset'),
        ),
    ]
