# Generated by Django 4.0.4 on 2022-06-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_strategy_algorithm_strategy_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='created',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='criterion',
            field=models.CharField(default='entropy', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='learning_rate',
            field=models.FloatField(default=0, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='max_depth',
            field=models.IntegerField(default=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='n_estimators',
            field=models.IntegerField(default=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='random_state',
            field=models.IntegerField(default=42, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='downs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ups',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
