# Generated by Django 4.0.4 on 2022-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_tag_asset_history_asset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='identifier',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
