# Generated by Django 4.0.4 on 2022-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_asset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='criterion',
            field=models.CharField(default='entropy', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='learning_rate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='max_depth',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='n_estimators',
            field=models.IntegerField(default=200, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='random_state',
            field=models.IntegerField(default=42, null=True),
        ),
    ]
