# Generated by Django 4.0.4 on 2022-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_algorithm_accuracy_alter_algorithm_criterion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='splitter',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
