# Generated by Django 3.2.13 on 2022-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_algorithm_splitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='prediction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='predictions_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='predictions_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='splitter',
            field=models.CharField(default='best', max_length=15, null=True),
        ),
    ]
