# Generated by Django 3.2.13 on 2022-06-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20220601_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sentiment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='identifier',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
