# Generated by Django 3.2.13 on 2022-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20220614_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='active',
            new_name='isactive',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='confidence',
            new_name='accuracy',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='history',
        ),
        migrations.AddField(
            model_name='asset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
