# Generated by Django 3.2.13 on 2022-08-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20220822_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='batch',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
