# Generated by Django 3.2.13 on 2022-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_asset_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='batch',
        ),
        migrations.AddField(
            model_name='asset',
            name='candles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
