# Generated by Django 3.2.13 on 2022-09-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20220916_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='algorithm',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.asset'),
        ),
    ]
