# Generated by Django 3.2.13 on 2022-09-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20220916_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='platformsymbol',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='base.asset'),
        ),
    ]
