# Generated by Django 3.2.13 on 2022-09-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20220920_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='name',
            new_name='identifier',
        ),
    ]
