# Generated by Django 3.2.13 on 2022-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_name_algorithm_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
