# Generated by Django 3.2.13 on 2022-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_algorithm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
