# Generated by Django 3.2.13 on 2022-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_asset_cg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_close',
            field=models.FloatField(default=0),
        ),
    ]
