# Generated by Django 3.2.13 on 2022-09-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_asset_last_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='last_tuning',
            field=models.DateTimeField(null=True),
        ),
    ]
