# Generated by Django 3.2.13 on 2022-09-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_algorithm_last_tuning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.CreateModel(
            name='HitratioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitratio', models.IntegerField(null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hitratio', to='base.asset')),
            ],
        ),
    ]
