# Generated by Django 3.2.13 on 2022-10-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_asset_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hitratiohistory',
            options={'verbose_name_plural': 'hitratiohistories'},
        ),
        migrations.AddField(
            model_name='hitratiohistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitratiohistory',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hitratios', to='base.asset'),
        ),
    ]
