# Generated by Django 3.2.13 on 2022-10-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20221005_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitratiohistory',
            name='hitratio',
            field=models.FloatField(default=0, null=True),
        ),
    ]
