version: '2.6'
services:
  app:
    restart: always
    build: 
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=M_Vy#]Vd4dSje592K2rJXM55E
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=0
      - DB_PW=dtupOEs4SA!Z7jSXYTdTb
      - DB_HOST=arqdb.cratkb3vsjdk.eu-west-3.rds.amazonaws.com
      - B_PK=WZWyDV3jEFP6c-xnoNtYbkhK
      - B_SK=E-wC7jcD65Bfy-4qnvbD4YWWTNET6cN_nARAAyP3io0re4ab
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: arq-api-logger
  
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: arq-proxy-logger

  celery:
    restart: always
    build: .
    command: "celery -A arq.celery worker -l info"
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: arq-celery-logger

  celery-beat:
    restart: always
    build: .
    command: "celery -A arq.celery beat -l info"

volumes:
  static_data:
