version: '2.2'
services:
  app:
    restart: always
    build: 
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=M_Vy#]Vd4dSje592K2rJXM55E
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=0
      - DB_PW=dtupOEs4SAZ7jSXYTdTb
      - DB_HOST=ghostdb.cratkb3vsjdk.eu-west-3.rds.amazonaws.com
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: ghost-api-logger
  
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: ghost-proxy-logger

  celery:
    restart: always
    build: .
    command: "celery -A arq.celery worker -l info"
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: ghost-celery-logger

  celery-beat:
    restart: always
    build: .
    command: "celery -A arq.celery beat -l info"

volumes:
  static_data:
